

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

CREATE TABLE IF NOT EXISTS `mydb`.`knihovna` (
  `id_kniha` INT NOT NULL,
  `nazev` VARCHAR(45) NOT NULL,
  `autor` VARCHAR(45) NOT NULL,
  `vydani` VARCHAR(45) NOT NULL,
  `dostupnost` VARCHAR(45) NOT NULL,
  `typ` VARCHAR(45) NOT NULL,
  `extra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kniha`)) 
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
